<?php

namespace Modules\Blog\Tests\Base;

use Modules\Blog\Entities\BlogTag;
use Modules\Core\Tests\TestCase;

abstract class BaseBlogTagsTest extends TestCase
{
    public function __construct()
    {
        parent::__construct();
        $this->index_route = 'blog-tags.index';
        $this->create_form_route = 'blog-tags.create';
        $this->store_route = 'blog-tags.store';
        $this->edit_form_route = 'blog-tags.edit';
        $this->update_route = 'blog-tags.update';
        $this->destroy_route = 'blog-tags.destroy';
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->entity = create(BlogTag::class);
    }
}
