<?php

namespace Modules\Blog\Tests\Base;

use Modules\Blog\Entities\BlogCategory;
use Modules\Core\Tests\TestCase;

abstract class BaseBlogCategoriesTest extends TestCase
{
    public function __construct()
    {
        parent::__construct();
        $this->index_route = 'blog-categories.index';
        $this->create_form_route = 'blog-categories.create';
        $this->store_route = 'blog-categories.store';
        $this->edit_form_route = 'blog-categories.edit';
        $this->update_route = 'blog-categories.update';
        $this->destroy_route = 'blog-categories.destroy';
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->entity = create(BlogCategory::class, ['parent_id' => null]);
    }
}
