<?php

namespace Modules\Blog\Tests\Base;

use Modules\Blog\Entities\BlogPost;
use Modules\Core\Tests\TestCase;

abstract class BaseBlogPostsTest extends TestCase
{
    public function __construct()
    {
        parent::__construct();
        $this->index_route = 'blog-posts.index';
        $this->create_form_route = 'blog-posts.create';
        $this->store_route = 'blog-posts.store';
        $this->edit_form_route = 'blog-posts.edit';
        $this->update_route = 'blog-posts.update';
        $this->destroy_route = 'blog-posts.destroy';
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->entity = create(BlogPost::class);
    }
}
