<?php

namespace Modules\Blog\Tests\Unit;

use Modules\Blog\Entities\BlogCategory;
use Modules\Blog\Entities\BlogPost;
use Modules\Core\Tests\TestCase;

class BlogPostsTest extends TestCase
{
    protected $post;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->post = create(BlogPost::class);
    }

    /** @test */
    public function blog_post_has_categories()
    {
        $categories = create(BlogCategory::class, ['parent_id' => null], 10);

        foreach ($categories as $category) {
            \DB::table('blog_category_post_pivot')->insert([
                'blog_category_id' => $category->id,
                'blog_post_id'     => $this->post->id
            ]);
        }

        $this->assertCount(10, $this->post->categories);
        foreach ($categories as $category) {
            $this->assertTrue($this->post->categories->contains($category));
        }
    }

    /** @test */
    public function blog_post_has_statuses()
    {
        $this->assertCount(2, $this->post->statuses());
    }

    /** @test */
    public function blog_post_has_statusName()
    {
        $this->assertTrue(is_string($this->post->statusName));
    }
}
