<?php

namespace Modules\Blog\Tests\Unit;

use Modules\Blog\Entities\BlogCategory;
use Modules\Blog\Entities\BlogPost;
use Modules\Core\Tests\TestCase;

class BlogCategoriesTest extends TestCase
{
    protected $category;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->category = create(BlogCategory::class, ['parent_id' => null]);
    }

    /** @test */
    public function blog_category_has_parent()
    {
        $childCategory = create(BlogCategory::class, ['parent_id' => $this->category]);
        $this->assertInstanceOf(BlogCategory::class, $childCategory->parent);
        $this->assertEquals($this->category->id, $childCategory->parent->id);
        $this->assertEquals($this->category->name, $childCategory->parent->name);
    }

    /** @test */
    public function blog_category_has_many_posts()
    {
        $posts = create(BlogPost::class, [], 10);
        foreach ($posts as $post) {
            \DB::table('blog_category_post_pivot')->insert([
                'blog_category_id' => $this->category->id,
                'blog_post_id'     => $post->id
            ]);
        }

        $this->assertCount(10, $this->category->posts);
        foreach ($posts as $post) {
            $this->assertTrue($this->category->posts->contains($post));
        }
    }

    /** @test */
    public function blog_category_has_statuses()
    {
        $this->assertCount(2, $this->category->statuses());
    }

    /** @test */
    public function blog_category_has_statusName()
    {
        $this->assertTrue(is_string($this->category->statusName));
    }
}
