<?php

namespace Modules\Blog\Tests\Feature;

use Modules\Blog\Entities\BlogCategory;
use Modules\Core\Tests\TestCase;

class ReadBlogCategoriesTest extends TestCase
{

    protected $category;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->category = create(BlogCategory::class, ['parent_id' => null]);
    }

    private function accessBlogCategoryList($overrides = [])
    {
        return $this->get(route('blog-categories.index', $overrides));
    }

    /** @test */
    public function unauthenticated_users_can_not_access_blog_categories_list()
    {
        $this->accessBlogCategoryList()
            ->assertRedirect(self::LOGIN_URL);
    }

    /** @test */
    public function authenticated_users_can_access_blog_categories_list()
    {
        $this->signIn();

        $this->accessBlogCategoryList()
            ->assertSee($this->category->name)
            ->assertSee($this->category->statusName);
    }

    /** @test */
    public function blog_categories_can_be_searched_by_name()
    {
        $this->signIn();
        $otherCategory = create(BlogCategory::class, ['parent_id' => null]);

        $this->accessBlogCategoryList([
            'filter[search]' => $this->category->name
        ])
            ->assertSee($this->category->name)
            ->assertDontSee($otherCategory->name);
    }
}
