<?php

namespace Modules\Blog\Tests\Feature;

use Modules\Blog\Entities\BlogTag;
use Modules\Core\Tests\TestCase;

class ReadBlogTagsTest extends TestCase
{
    protected $tag;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->tag = create(BlogTag::class);
    }

    private function accessTagList($overrides = [])
    {
        return $this->get(route('blog-tags.index', $overrides));
    }

    /** @test */
    public function unauthenticated_users_can_not_view_blog_tag_list()
    {
        $this->accessTagList()
            ->assertRedirect(self::LOGIN_URL);
    }

    /** @test */
    public function authenticated_users_can_view_blog_tag_list()
    {
        $this->signIn();

        $this->accessTagList()
            ->assertSee($this->tag->name);
    }

    /** @test */
    public function blog_tag_can_be_searched_by_name()
    {
        $this->signIn();
        $otherTag = create(BlogTag::class);

        $this->accessTagList(['filter[search]' => $this->tag->name])
            ->assertSee($this->tag->name)
            ->assertDontSee($otherTag->name);
    }
}
