<?php

namespace Modules\Blog\Tests\Feature;

use Modules\Blog\Entities\BlogCategory;
use Modules\Core\Tests\TestCase;

class UpdateBlogCategoriesTest extends TestCase
{
    protected $category;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->category = create(BlogCategory::class, ['parent_id' => null]);
    }

    private function accessEditCategoryForm()
    {
        return $this->get(route('blog-categories.edit', $this->category->id));
    }

    private function updateBlogCategory($overrides = [])
    {
        return $this->patch(route('blog-categories.update', $this->category->id), $overrides);
    }

    /** @test */
    public function unauthenticated_users_can_not_access_edit_category_form()
    {
        $this->accessEditCategoryForm()
            ->assertRedirect(self::LOGIN_URL);
    }

    /** @test */
    public function authenticated_users_can_access_edit_category_form()
    {
        $this->signIn();

        $this->accessEditCategoryForm()
            ->assertSee($this->category->name)
            ->assertSee($this->category->statusName)
            ->assertSee($this->category->thumbnail);
    }

    /** @test */
    public function unauthenticated_users_can_not_update_blog_category()
    {
        $this->updateBlogCategory()
            ->assertRedirect(self::LOGIN_URL);
    }

    /** @test */
    public function authenticated_users_can_update_blog_category()
    {
        $this->withoutExceptionHandling();
        $this->signIn();

        $this->updateBlogCategory([
            localize_field('name') => 'updated',
            'status'               => 1,
            'parent_id'            => 0,
        ])->assertRedirect(route('blog-categories.index'));

        tap($this->category->fresh(), function ($category) {
            $this->assertEquals('updated', $category->name);
            $this->assertEquals(1, $category->status);
        });
    }

    /** @test */
    public function update_blog_category_requires_name_and_status_and_parent_id()
    {
        $this->signIn();

        $this->updateBlogCategory()
            ->assertSessionHasErrors([localize_field('name'), 'status', 'parent_id']);
    }
}
