<?php

namespace Modules\Product\Tests\Base;

use Modules\Core\Tests\TestCase;
use Modules\Product\Entities\ProductCategory;

abstract class BaseProductCategoriesTest extends TestCase
{
    public function __construct()
    {
        parent::__construct();
        $this->index_route = 'product-categories.index';
        $this->create_form_route = 'product-categories.create';
        $this->store_route = 'product-categories.store';
        $this->edit_form_route = 'product-categories.edit';
        $this->update_route = 'product-categories.update';
        $this->destroy_route = 'product-categories.destroy';
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->entity = create(ProductCategory::class);
    }
}
