<?php

namespace Modules\Product\Tests\Base;

use Modules\Core\Tests\TestCase;
use Modules\Product\Entities\ProductTag;

abstract class BaseProductTagsTest extends TestCase
{
    public function __construct()
    {
        parent::__construct();
        $this->index_route = 'product-tags.index';
        $this->create_form_route = 'product-tags.create';
        $this->store_route = 'product-tags.store';
        $this->edit_form_route = 'product-tags.edit';
        $this->update_route = 'product-tags.update';
        $this->destroy_route = 'product-tags.destroy';
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->entity = create(ProductTag::class);
    }
}
