<?php

namespace Modules\Product\Tests\Base;

use Modules\Core\Tests\TestCase;
use Modules\Product\Entities\Brand;

abstract class BaseBrandsTest extends TestCase
{
    public function __construct()
    {
        parent::__construct();
        $this->index_route = 'brands.index';
        $this->create_form_route = 'brands.create';
        $this->store_route = 'brands.store';
        $this->edit_form_route = 'brands.edit';
        $this->update_route = 'brands.update';
        $this->destroy_route = 'brands.destroy';
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->entity = create(Brand::class);
    }
}
